### ISSUE TITLE
Empty screen in imap mode, crash after keypresses

### ISSUE THREAD

**Issue by gber** [lumail/lumail2#138] opened 2016-01-21 15:01 UTC
I wanted to try out the new imap mode, however lumail does not display anything, ie. only the "Status Panel" at the bottom is shown, the rest of the screen is empty. It also does not seem to react to keypresses and pressing "i" or tab multiple times crashes lumail.

I'm running the latest available code from git, currently commit 1824a4f5fcae91dc9464b4be476f0019c45809b5

My configuration is as follows (personal details removed):

    $ cat .lumail2/lumail2.lua
    Config:set( "imap.cache", "/home/gber/.lumail2/cache/" )
    Config:set( "imap.server",   "imaps://XXX/" )
    Config:set( "imap.username", "XXXX" )
    Config:set( "imap.password", "XXXX" )

When starting lumail2 I can see via tcpdump that it is retrieving the list of IMAP mailboxes from my server. I'm not sure if the above configuration is enough or what is supposed to happen after startup, is it supposed to open the INBOX or show a list of mailboxes?

[Backtrace from the crash](https://github.com/lumail/lumail2/files/99300/gdb.txt)

**Comment by skx** [comment] 2016-01-21 15:28
I'll need to look at this in depth to work out where the crash is happening, but I can tell you that the reason you're seeing the fault is that your configuration-file is not complete.

Lumail calls out to lua to display the various modes, and handle keyboard lookup.  What you should probably do is:

* Copy the lumail2.lua configuration file to your `~/.lumail2/lumail2.lua` file.
* Create ~/.lumail2/$hostname.lua with your personal config in it.   Those IMAP-specific lines you quote.
     * Or just append to the default file.  

I suspect what is happening is that the program is trying to lookup the value of the keymap - to know how to handle the key you've pressed - finding it misisng, and then dying horribly.

Even if you populated the keymap you'd soon find another crash, because the user-interface is created by Lua, and you've not defined `maildir_view()`, `message_view()`, etc.

FWIW You're supposed to see a list of folders.  Then you select one, and you see the messages in it, then you select one and you see the message, and if you wish you can press `A` to see the MIME-structure/attachments.

**Comment by skx** [comment] 2016-01-21 16:01
Ahh, I misunderstood.  You do load _both_ the global and the personal file.

I'll try to reproduce tonight.

**Comment by gber** [comment] 2016-01-21 16:08
Thanks for the clarification. No, you were right I did not have a global lumail2.lua and after copying it to ~/.lumail2/ it actually shows the list of mailboxes. Would it make sense to have `make install` copy lumail2.lua to /etc/lumail2 so that it works out of the box?

**Comment by skx** [comment] 2016-01-21 16:11
There was a bug report in the past about trashing users' global files if I did a blind copy.

But certainly I can configure it such that `make install` will copy the file if it isn't already present.

I'll commit that tonight, and close this issue then.

Thanks for the bug report :)

**Closed** 2016-01-21 19:35 UTC
Labels: imap
